# Generated by Django 3.1.6 on 2021-02-14 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of rss feed.', max_length=50, unique=True)),
                ('link', models.CharField(help_text='Link of rss feed.', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('followers', models.ManyToManyField(through='feed.FollowRss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='followrss',
            name='rss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.rss'),
        ),
        migrations.AddField(
            model_name='followrss',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of feed.', max_length=200)),
                ('link', models.CharField(help_text='Link of feed.', max_length=500)),
                ('published', models.IntegerField(help_text='Epoch Time of feed.')),
                ('description', models.CharField(help_text='Description of feed.', max_length=2000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('favorites', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('rss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.rss')),
            ],
            options={
                'ordering': ('-published',),
                'unique_together': {('link', 'published')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(help_text='Body of comment.', max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.IntegerField(default=1613286873, help_text='Epoch Time of comment creation.')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
